# Install script for directory: /home/chris/Source/build/bullet-2.77/Demos

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/usr/local")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Release")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/OpenGL/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/AllBulletDemos/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/ConvexDecompositionDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/HelloWorld/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/CcdPhysicsDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/ConstraintDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/SliderConstraintDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/GenericJointDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/Raytracer/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/RagdollDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/ForkLiftDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/BasicDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/Box2dDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/BspDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/MovingConcaveDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/VehicleDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/UserCollisionAlgorithm/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/CharacterDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/SoftDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/HeightFieldFluidDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/CollisionInterfaceDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/ConcaveConvexcastDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/SimplexDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/DynamicControlDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/DoublePrecisionDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/ConcaveDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/CollisionDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/ContinuousConvexCollision/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/ConcaveRaycastDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/GjkConvexCastDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/MultiMaterialDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/SerializeDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/InternalEdgeDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/Benchmarks/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/ThreadingDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/MultiThreadedDemo/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/VectorAdd_OpenCL/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/ParticlesOpenCL/cmake_install.cmake")
  INCLUDE("/home/chris/Source/build/bullet-2.77/Demos/OpenCLClothDemo/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

